# Generated by Django 4.0.4 on 2022-10-08 13:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titles', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectname', models.CharField(max_length=100)),
                ('projectdscp', models.CharField(max_length=500, null=True)),
                ('goal', models.IntegerField()),
                ('deadline', models.CharField(max_length=10)),
                ('key', models.CharField(max_length=16)),
                ('image_uploaded', models.ImageField(default=True, null=True, upload_to='uploaded_images/')),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('video_uplaoded', models.FileField(blank=True, null=True, upload_to='uploaded_videos/')),
                ('projectby', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Project List',
            },
        ),
    ]
