# Generated by Django 4.0.4 on 2022-10-08 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ethfund_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='projectby',
        ),
    ]
