# Generated by Django 4.0.4 on 2022-10-09 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ethfund_app', '0003_projects_projectby'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='slug',
            field=models.SlugField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
