# Generated by Django 4.0.4 on 2022-10-09 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ethfund_app', '0004_projects_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='slug',
        ),
    ]
