# Generated by Django 4.0.4 on 2022-12-14 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ethfund_app', '0005_remove_projects_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='wallet_addr',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
