# Generated by Django 4.0.4 on 2022-12-15 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ethfund_app', '0006_projects_wallet_addr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='key',
            field=models.CharField(max_length=1000),
        ),
    ]
